export enum ActionError {
  SERVER_TIMEOUT = "SERVER_TIMEOUT",

  OUTCOME_MISSING = "OUTCOME_MISSING",
  OUTCOME_INVALID = "OUTCOME_INVALID",

  INPUT_IMAGE_MISSING = "INPUT_IMAGE_MISSING",
  INPUT_IMAGE_TOO_LARGE = "INPUT_IMAGE_TOO_LARGE",
  INPUT_IMAGE_TYPE_NOT_ALLOWED = "INPUT_IMAGE_TYPE_NOT_ALLOWED",
}