/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/runsync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Prompt */
                        prompt: string;
                        /**
                         * Height
                         * @default 512
                         */
                        height?: number;
                        /**
                         * Width
                         * @default 512
                         */
                        width?: number;
                        /**
                         * Guidance Scale
                         * @default 1
                         */
                        guidance_scale?: number;
                        /**
                         * Num Inference Steps
                         * @default 4
                         */
                        num_inference_steps?: number;
                        /**
                         * Seed
                         * @default null
                         */
                        seed?: number | null;
                        /**
                         * Input Image
                         * @default null
                         */
                        input_image?: string | null;
                        /** Reference Images */
                        reference_images?: string[];
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Image */
                            image: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Prompt */
                        prompt: string;
                        /**
                         * Height
                         * @default 512
                         */
                        height?: number;
                        /**
                         * Width
                         * @default 512
                         */
                        width?: number;
                        /**
                         * Guidance Scale
                         * @default 1
                         */
                        guidance_scale?: number;
                        /**
                         * Num Inference Steps
                         * @default 4
                         */
                        num_inference_steps?: number;
                        /**
                         * Seed
                         * @default null
                         */
                        seed?: number | null;
                        /**
                         * Input Image
                         * @default null
                         */
                        input_image?: string | null;
                        /** Reference Images */
                        reference_images?: string[];
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
