/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Prompt = string;
export type Height = number;
export type Width = number;
export type InputImage = string | null;
export type ReferenceImages = string[] | null;

export interface RequestPayload {
  prompt: Prompt;
  height: Height;
  width: Width;
  input_image?: InputImage;
  reference_images?: ReferenceImages;
  [k: string]: unknown;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Image = string;

export interface ResponsePayload {
  image: Image;
  [k: string]: unknown;
}
